spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: szy
    password: 318675
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.oracle.pojo
